name: Release-Canary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build --verbose
      - run: |
          cd ./packages/dw-react-controls
          ls -R
      - run: yarn test
      - run: |
          git config --global user.email "nick.sevens@delaware.pro"
          git config --global user.name "Nick Sevens"
      # - run: |
      #     yarn release:canary -y \
      #       -r "https://npm.pkg.github.com/" \
      #       -n $NPM_AUTHTOKEN \
      #       --canaryName $CI_REF_NAME_SLUG \
      #       --no-git-tags \
      #       -t exper
      #   env:
      #     NPM_AUTHTOKEN: ${{secrets.GITHUB_TOKEN}}
